{
  products {
    _id
    title
    supplier {
      first_name
      last_name
    }
    text
    images
    imagesURL
    features {
      length
      height
      width
      weight
      color
      madein
    }
    category{
      title
    }
  }
}
